config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]
  resources :requests
  resources :applies, only: [:create, :destroy]
  resources :diplomas, only: [ :create, :destroy]
  resources :conversations, only: [:new ,:create, :show, :update]
  put "close_conversation", to: "conversations#close"
  resources :messages, only: [:create]

  mount ActionCable.server, at: '/cable'
  mount RailsAdmin::Engine => "/admin", as: :rails_admin
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :sender, class_name: User.name, optional: true
  belongs_to :receiver, class_name: User.name
end

app/views/notifications/_notification.html.erb
<li>
  <div class="col-md-3 col-sm-3 col-xs-3"><div class="notify-img"><img src="http://placehold.it/45x45" alt=""></div></div>
  <div class="col-md-9 col-sm-9 col-xs-9 pd-l0"><a href=""><%= notification.sender.email %></a><a href=""></a><a href="" class="rIcon"><i class="fa fa-dot-circle-o"></i></a>
    <p><%= notification.event %></p>
    <% if notification.object_type == "request" %>
      <p> <%= link_to t("views.layouts.header.redirect_to"),request_path(notification.object_id), class: "btn btn-success" %></p>
    <% elsif notification.object_type == "conversation" %>
      <p> <%= link_to t("views.layouts.header.redirect_to"),conversation_path(notification.object_id), class: "btn btn-success" %></p>
    <% end %>
    <p class="time"><%= notification.created_at %></p>
  </div>
</li>