config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]
  resources :requests
  resources :applies, only: [:create, :destroy]
  resources :diplomas, only: [ :create, :destroy]
  resources :conversations, only: [:new ,:create, :show, :update]
  put "close_conversation", to: "conversations#close"
  resources :messages, only: [:create]

  mount ActionCable.server, at: '/cable'
  mount RailsAdmin::Engine => "/admin", as: :rails_admin
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_many :reviews, foreign_key: :user_id, dependent: :destroy
  has_many :experts, class_name: Conversation.name, foreign_key: :expert_id, dependent: :destroy
  has_many :newbies, class_name: Conversation.name, foreign_key: :newbie_id, dependent: :destroy
  has_many :messages, foreign_key: :user_id, dependent: :destroy
  has_many :applies, foreign_key: :user_id, dependent: :destroy
  has_many :appling, through: :applies, source: :request
  has_many :payments, foreign_key: :user_id, dependent: :destroy
  has_many :diplomas, foreign_key: :user_id, dependent: :destroy
  has_many :requests, foreign_key: :user_id, dependent: :destroy
  has_many :send_notifications, foreign_key: :sender_id, class_name: Notification.name, dependent: :delete_all
  has_many :receive_notifications, foreign_key: :receiver_id, class_name: Notification.name, dependent: :delete_all

  class << self
    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
      end
    end

    def new_with_session params, session
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth request.env["omniauth.auth"]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message :notice, :success, kind: "Facebook"  if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    signed_in_root_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    signed_in_root_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
   def new
     self.resource = resource_class.new sign_in_params
     store_location_for(resource, params[:redirect_to])
     super
   end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource param_method: :user_params

  def show
    @user = User.find_by id: params[:id]
    @diplomas_pending = @user.diplomas.verify(false).page(params[:page]).per(Settings.request.per)
    @diplomas_approved = @user.diplomas.verify(true).page(params[:page]).per(Settings.request.per)
    @diploma = Diploma.new
    return if @user
    flash[:danger] = t "controllers.users.show.danger"
    redirect_to root_url
  end

  def index
    @q = User.ransack params[:q]
    @q.sorts = "name asc" if @q.sorts.empty?
    @users = @q.result.includes(:requests).page(params[:page]).per(Settings.request.per)
  end

  def search
    render :index
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
    :password_confirmation, :avatar, :description, :adress, :sex
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user_diplomas(user)
    user.diplomas.verify(true)
  end
end

app/views/users/_applier.html.erb
<li id="user-apply-<%= applier.id %>">
  <div id="comment-food">
    <div class="row">
      <div class="col-md-6">
        <img src ="https://cdn1.iconfinder.com/data/icons/user-pictures/101/malecostume-512.png" height="40" width="40">&nbsp;
        <%= link_to applier.name, "#my-modal-#{applier.id}", "data-toggle" => "modal" %>
          <div class="modal" id="my-modal-<%= applier.id %>" title="My modal">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><%= t "views.users.show.diploma" %></h4>
              </div>
              <div class="modal-body">
                <%= render partial: "users/diploma", collection: current_user_diplomas(applier), as: :diploma %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                  <%= t "views.users.show.close" %>
                </button>
              </div>
            </div>
          </div>
      </div>
      <div class="col-md-6">
        <% if user_signed_in? %>
          <div class="col-md-6">
            <% if applier.free? %>
              <%= button_to t("views.requests.show.accept"), conversations_url(applier_id: applier.id, request_id: request_id),
                 class:"btn btn-success accept-apply", id: applier.id %>
            <% else %>
              <button class="btn btn-warning"><%= t "views.requests.show.user_busy" %></button>
            <% end %>
          </div>
          <div class="col-md-3">
            <%= button_to "X", {controller: :applies, action: :destroy, id: Apply.find_apply(request_id, applier.id) },
                          :method => :delete, class:"btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
    <hr>
    <div id="comment-content">
    </div>
  </div>
</li>

app/views/users/_diploma.html.erb
<%= diploma.certification %>
</br>

app/views/users/index.html.erb
<h1 class="text-center"><%= t "views.users.index.title" %></h1>
  <%= render "layouts/search_form"%>
  <br>
<%- @users.each do |user| %>
  <div class="container">
    <div class="panel-body">
      <div class="box box-info">
        <div class="box-body">
          <br>
          <div class="col-sm-6">
            <h4><%= user.name %></h4></span>
          </div>
          <div class="clearfix"></div>
          <hr>
          <div class="col-sm-5 col-xs-6 tital ">
            <%= t "views.users.show.email" %>:</div>
          <div class="col-sm-7">
            <%= user.email %>
          </div>
          <div class="clearfix"></div>
          <div class="bot-border"></div>
          <br>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @users %>

app/views/users/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4><%= t "views.users.show.head" %></h4>
  </div>
  <div class="panel-body">
    <div class="box box-info">
      <div class="box-body">
        <div class="col-sm-6">
          <div align="center"> <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive">
            <input id="profile-image-upload" class="hidden" type="file">
            <div style="color:#999;">
              <%= t "views.users.show.click" %>
            </div>
          </div>
          <br>
        </div>
        <div class="col-sm-6">
          <h4><%= @user.name %></h4></span>
        </div>
        <div class="clearfix"></div>
        <hr>
        <div class="col-sm-5 col-xs-6 tital ">
          <%= t "views.users.show.email" %>:</div>
        <div class="col-sm-7">
          <%= @user.email %>
        </div>
        <div class="clearfix"></div>
        <div class="bot-border"></div>
        <div class="col-sm-5 col-xs-6 tital ">
          <%= t "views.users.show.sex" %>:</div>
        <div class="col-sm-7">
          <%= @user.sex %>
        </div>
        <div class="clearfix"></div>
        <div class="bot-border"></div>
        <div class="col-sm-5 col-xs-6 tital ">
          <%= t "views.users.show.address" %>:</div>
        <div class="col-sm-7">
          <%= @user.address %>
        </div>
        <div class="clearfix"></div>
        <div class="bot-border"></div>
        <div class="col-sm-5 col-xs-6 tital ">
          <%= t "views.users.show.description" %>:</div>
        <div class="col-sm-7">
          <%= @user.description %>
        </div>
        <br>
        <% if user_signed_in? %>
          <% if current_user == @user %>
            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">
              <%= t "views.users.show.add_diploma" %>
            </button>
          <%end%>
        <%end%>
        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
          <div class="modal-dialog">
              <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><%= t "views.users.show.diploma" %></h4>
              </div>
              <div class="modal-body">
                <%= render "diplomas/modal_form" %>
              </div>
              <div class=" list-add">
                <p>
                  <%= t "views.users.show.list-add" %>
                </p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                  <%= t "views.users.show.close" %>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div>
  <ol class="diplomas">
    <h3><%= t "views.users.show.diploma" %> (<%= @diplomas_approved.count %>)</h3>
    <div class="list-diploma">
      <% if @user.diplomas.any? %>
        <% if current_user == @user %>
        <div class="list-pending">
          <p> <%= t "views.users.show.pending" %></p>
          <%= render partial: "diplomas/diploma", locals:{diplomas: @diplomas_pending} %>
        </div>
        <div class="list-approved">
          <p> <%= t "views.users.show.approved" %></p>
          <%= render partial: "diplomas/diploma", locals:{diplomas: @diplomas_approved} %>
        </div>
        <% else %>
          <div class="list-approved">
            <%= render partial: "diplomas/diploma", locals:{diplomas: @diplomas_approved} %>
          </div>
        <% end %>
      <% end %>
    </div>
  </ol>
</div>