config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]
  resources :requests
  resources :applies, only: [:create, :destroy]
  resources :diplomas, only: [ :create, :destroy]
  resources :conversations, only: [:new ,:create, :show, :update]
  put "close_conversation", to: "conversations#close"
  resources :messages, only: [:create]

  mount ActionCable.server, at: '/cable'
  mount RailsAdmin::Engine => "/admin", as: :rails_admin
end

app/models/request.rb
class Request < ApplicationRecord
  enum topic: {Math: 0, IT: 1, Literary: 2, History: 3, Chemistry:4, Physics: 5, Other: 6}
  enum status: {Applying: 1, Done: 2}
  has_many :applies, dependent: :destroy
  has_many :appliers, -> { order free: :desc }, through: :applies, source: :user
  belongs_to :user
  has_one :conversation, dependent: :destroy
  validates :bill, presence: true, numericality: { only_float: true },format: {with: /[0-9]*\.[0-9]*/}
  validates :header, presence: true, length: {minimum: Settings.request.header.minimum}
  validates :content, presence: true, length: {minimum: Settings.request.content.minimum}

  scope :request_applying, -> {where(status: :Applying).order(created_at: :desc)}

  scope :hot_topic, -> {select(:topic).group(:topic).where(status: :Applying).limit(Settings.home.hot_topic_count)}

  scope :request_by_topic, -> topic {where(status: :Applying, topic: topic).order created_at: :desc}

  def is_user? other_id
    user_id == other_id
  end

  def is_done?
    return true if status == "Done"
    false
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :find_request, except: [:new, :create, :index]

  def new
    @request_user = Request.new
  end

  def create
    request_user = current_user.requests.new request_params
    if request_user.save
      flash[:success] = t "controllers.requests.create.success"
      redirect_to root_url
    else
      flash[:danger] = t "controllers.requests.create.form_fail"
      redirect_to request.referrer
    end
  end

  def index
    @requests = current_user.requests.page(params[:page]).per(Settings.request.per)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def edit
  end

  def update
    if @request.update_attributes request_params
      flash[:success] = t "controllers.requests.update.success"
      redirect_to root_path
    else
      flash[:danger] = t "controllers.requests.update.danger"
      render :edit
    end
  end

  def show
    @appliers = @request.appliers
  end

  def destroy
    if @request.destroy
      respond_to do |format|
        format.html {redirect_to requests_url}
        format.js
      end
    else
      flash[:danger] = t "controllers.requests.destroy.danger"
      redirect_to requests_url
    end
  end

  private

  def request_params
    params.require(:request).permit :topic, :content, :header, :bill
  end

  def find_request
    @request = Request.find_by id: params[:id]

    return if @request
    flash[:danger] = t "controllers.requests.get_request.not_found"
    redirect_to root_url
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_request.html.erb
<div class="job-list" id="<%= request.id %>">
  <div class="thumb">
    <a href="job-details.html"><img src="" alt=""></a>
  </div>
  <div class="job-list-content">
    <h4>
      <a href="<%= request_path(request.id) %>"><%= request.header %></a>
      <span class="<%= request.status %>"><%= request.status %></span>
    </h4>
    <p><%= request.content %></p>
    <div class="job-tag request">
      <div class="pull-left">
        <div class="meta-tag">
          <span><i class="ti-brush"></i><%= request.topic %></span>
          <span><i class="ti-time"></i><%= request.bill %> $</span>
        </div>
      </div>
      <div class="pull-right">
        <div class="icon">
        </div>
        <a href="<%= request_path(request.id) %>" class="btn btn-common btn-rm">
          <%= t "views.requests.index.more_detail" %>
        </a>
        <% if user_signed_in? && request.is_user?(current_user.id) %>
          <span id="delete-request">
            <%= link_to request, method: :delete, data: {confirm: t("views.requests.show.confirm")}, remote: true do %>
              <i class="fa fa-times" aria-hidden="true"></i>
            <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/requests/destroy.js.erb
$("#<%= @request.id %>").remove();

app/views/requests/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4" >
      <div class="panel panel-primary">
        <div class="panel-heading"><%= link_to @request.header , @request %></div>
          <div class="panel-body">
            <%= form_for @request do |f|%>
              <div class="form-group">
                <label for="content"><%= t "views.requests.new.topic" %></label><br>
                <%= f.select :topic, Request.topics.map { |key, value| [key.humanize, key] }, {}, {class: "form-control"} %>
              </div>

              <div class="form-group">
                <label for="example-text-input" class="col-2 col-form-label"><%= t "views.requests.new.header" %></label>
                <%= f.text_field :header, class: "form-control"%>
              </div>

              <div class="form-group">
                <label for="content"><%= t "views.requests.new.content" %></label><br>
                <%= f.text_area :content, class: "form-control" %>
              </div>

                <label for="bill"><%= t "views.requests.new.bill" %></label><br>

              <div class="input-group">
                <%= f.text_field :bill, class: "form-control"%>
                <span class="input-group-addon" id="basic-addon2">VNĐ</span>
              </div>
              <br>

              <%= f.submit t("views.requests.new."), class: "btn btn-success" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
<section class="find-job section">
  <div class="container">
    <h2 class="section-title"><%= t "views.requests.index.my_requests" %></h2>
    <div class="row">
      <div class="col-md-12" id="requests">
        <%= render @requests %>
      </div>
      <div id="paginate"><%= paginate @requests, remote: true %></div>
    </div>
  </div>
</section>

app/views/requests/index.js.erb
$("#requests").html('<%= j render(@requests) %>')
$("#paginate").html('<%= j paginate(@requests, remote: true) %>')

app/views/requests/new.html.erb
<div class="container">
  <h1 class="text-center" ><%= t "views.layouts.header.create_request" %></h1>
  <%= form_for @request_user do |f|%>
    <div class="form-group">
      <label for="content"><%= t "views.requests.new.topic" %></label><br>
      <%= f.select :topic, Request.topics.map { |key, value| [key.humanize, key] }, {}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <label for="example-text-input" class="col-2 col-form-label"><%= t "views.requests.new.header" %></label>
      <%= f.text_field :header, required: true, class: "form-control"%>
    </div>
    <div class="form-group">
      <label for="content"><%= t "views.requests.new.content" %></label><br>
      <%= f.text_area :content, required: true, class: "form-control" %>
    </div>
      <label for="bill"><%= t "views.requests.new.bill" %></label><br>
    <div class="input-group">
      <%= f.text_field :bill, required: true, class: "form-control" , style: "height: 20%"%>
      <span class="input-group-addon" id="basic-addon2">VNĐ</span>
    </div>
    <br>
    <% if user_signed_in? %>
      <%= f.submit "Submit",class: "btn btn-success" %>
    <% else %>
      <a href="#loginModal" data-toggle="modal" id="login-button" class="btn btn-success"><%= t "views.requests.new.submit" %></a>
    <% end %>
  <% end %>
</div>
<%= javascript_include_tag "validate_request" %>

app/views/requests/show.html.erb
<section class="find-job section">
  <div class="container">
    <div class="row">
      <div class="col-md-12" id="requests-<%= @request.id %>">
        <div class="job-list">
          <div class="thumb">
            <a href="job-details.html"><img src="" alt=""></a>
          </div>
          <div class="job-list-content">
            <h4><%= @request.header %></a><span class="<%= @request.status %>"><%= @request.status %></span></h4>
            <p><%= @request.content %></p>
            <div class="job-tag request">
              <div class="pull-left">
                <div class="meta-tag">
                  <span><a href="browse-categories.html"><i class="ti-brush"></i><%= @request.topic %></a></span>
                  <span><i class="ti-time"></i><%= @request.bill %> $</span>
                </div>
              </div>
              <div class="pull-right">
                <% unless @request.is_done? %>
                  <% if user_signed_in? %>
                    <% if !@request.is_user?(current_user.id) %>
                      <%= button_to t("views.requests.show.apply"), applies_url(request_id: @request.id),
                                class: "btn btn-success", remote: true %>
                    <% end %>
                  <% else %>
                    <a href="#loginModal" data-toggle="modal" id="login-button" class="btn btn-success">
                        <%= t "views.requests.show.apply" %></a>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="container">
  <div class="row">
    <% unless @request.is_done? %>
    <div class="col-6 col-md-4" >
      <h5><b><%= t "views.requests.show.appliers" %></b></h5>
        <div style=" word-wrap: break-word;">
          <ul id="list-appliers-<%=@request.id %>">
            <% @appliers.each do |applier| %>
              <%= render partial: "users/applier", locals: {applier: applier, request_id: @request.id}%>
            <% end %>
          </ul>
        </div>
    </div>
    <% end %>
    <div class="col-12 col-md-8">
      <h5><b><%= t "views.requests.show.comments" %></b></h5>
    </div>
  </div>
</div>